apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}-config
data:
  cluster-id: "{{ .Values.cluster.id }}"
  server.properties: |
{{ .Values.serverProperties | indent 4 }}
